### ISSUE TITLE
httpsエラー対応

### ISSUE THREAD

**Issue by watilde** [nodejsjp/nodejsjp.github.com#218]
https://github.com/nodefest/nodefest.github.com/issues/53 と同じそう
+ https://nodejs.jp

**Comment by abouthiroppy** [comment]
早いうちに解決したいですね、この問題。。

**Comment by kt3k** [comment]
@tgfjt さんのいうように cloudflare を被せるか、custom domain TLS が効く static site hosting に移すか、どちらかですかね、(firebase hosting, gitlab pages, netlify あたりは、無料で custom domain TLS 出来るようです。 https://github.com/255kb/stack-on-a-budget/blob/master/pages/static-app-hosting.md

**Comment by abouthiroppy** [comment]
閉じで良さそう？

**Comment by watilde** [comment]
:tada:
