### ISSUE TITLE
ローカルにチェックアウトしなくても記事を書けるようにしたい

### ISSUE THREAD

**Issue by kt3k** [nodejsjp/nodejsjp.github.com#239]
- git 操作/ファイル操作が面倒なので、ブラウザ上で完結して記事を書けるようにしたい

**Comment by abouthiroppy** [comment]
`Create new file` とpreviewでどうにかなりそうですか？

**Comment by kt3k** [comment]
ビルドの仕組みを把握していれば、それでも書けそうですが、初めての人/ビルドしたことない人には厳しい気がしています。
あと、例えば、2017-07-10 のイベントを追加したい場合は、source/events/2017/07-10-event-name.md 的なファイル名をつける感じの運用ルールになんとなくなってきているんですが、このファイル名をきちんとつけるみたいなところも、若干面倒なのかなぁと言う気がしています・・・、
あとは、フロントマターのプロパティーが覚えられない的な話もある気がします・・

**Comment by kt3k** [comment]
issue とか PR のテンプレート機能みたいなのが、Create new file に対してもあったら、かなりやりたいことが実現できそうな気がしています

**Comment by kt3k** [comment]
memo: https://twitter.com/azu_re/status/893766745265127424
